### ISSUE TITLE
Suggestion: Multiple selections on one Builder?

### ISSUE THREAD

**Issue by Imaginary-Narwhal** [d4n3436/Fergun.Interactive#12]
Pretty sure it wouldn't be possible (probably constrained by Discord itself) but could it be possible ot have more than one drop down selection on a builder? My idea is having 3 selections for choosing a time. Example: Hour : Minute  period dropdowns.

**Comment by d4n3436** [comment]
Duplicate of #6.

Note: I've added some examples on how to make custom selections some minutes ago.
There's an example for multiple select menus/dropdowns in a single message [here](https://github.com/d4n3436/Fergun.Interactive/blob/master/ExampleBot/Modules/CustomSelectModule.cs).
