### ISSUE TITLE
Way to combine page number footer with own custom footer

### ISSUE THREAD

**Issue by th0mk** [d4n3436/Fergun.Interactive#2]
I would like to have the option to show my own footer, but still combine it with the page number footer in some way. I couldn't find an option for this, so I don't think it exists yet.

Some examples for what I'd like to show in my footer are:

`Page 1/10 - 200 total results`

 `Page 1/8 - Last updated - 22:38` (embed footer timestamp)

**Comment by d4n3436** [comment]
`PaginatorFooter` is meant to be an easy way to add a footer with page/user info to a paginator without having to do it manually, but writing a custom footer that also displays the page number is also easy:

Static paginator:

```cs
var list = GetResults(); // Some list to get the page info from
var pages = new List<PageBuilder>();

for (int i = 0; i < list.Count; i++)
{
    var page = new PageBuilder()
        .WithDescription(list[i].Data)
        .WithFooter($"Page {i + 1}/{list.Count} - {list.Results} total results");

    pages.Add(page);
}

var builder = new StaticPaginatorBuilder()
    .WithPages(pages)
    .WithFooter(PaginatorFooter.None)
    ...
```

Lazy paginator:

```cs
var list = GetResults();
var builder = new LazyPaginatorBuilder()
    .WithPageFactory(GeneratePageAsync)
    .WithFooter(PaginatorFooter.None)
    ...

Task<PageBuilder> GeneratePageAsync(int index)
{
    var page = new PageBuilder()
        .WithDescription(list[index].Data)
        .WithFooter($"Page {index + 1}/{list.Count} - Last updated")
        .WithTimestamp(list[index].Timestamp);

    return Task.FromResult(page);
}
```

Adding an option to combine the footers would add unnecessary complexity imo. The part that generates the page number is already [very simple](https://github.com/d4n3436/Fergun.Interactive/blob/046e1c52b49fa93a05b099f8d765b1b3b85c65b4/src/Entities/Page/PageBuilder.cs#L426-L429).

**Comment by th0mk** [comment]
Oh 🤦‍♂️can't believe I didnt think of simply solving it that way. Thank you.
