### ISSUE TITLE
Select more than one option in one select menu.

### ISSUE THREAD

**Issue by Jonasfxh** [d4n3436/Fergun.Interactive#27]
I used the example for adding 2 select menu (one after another), but I would like to be able to select multiple options in one of them, is this possible?

I made some changes to the code to be able to send one select menu to accept multiple selection, but in the code I only received one string.
![multi selection in one select menu](https://github.com/d4n3436/Fergun.Interactive/assets/8949219/4cafa886-118e-4060-af0f-622a5aae9ef2)

in the SendSelectionAsync() method I only get one value, I can't find a way to understand how this method received what the user send through the select menu with multi selection.

![image](https://github.com/d4n3436/Fergun.Interactive/assets/8949219/65f0e306-ad53-4bc4-8f64-de2e373cc655)

**Comment by Jonasfxh** [comment]
I was trying to make this feature but the this project doesn't work on my local
I have spent almost 2 days trying to build the fergun.interactive source, but it says "it can't find the same library project dll"

Severity Code Description Project File Line Suppression State Error MSB3030 Could not copy the file obj\Debug\netstandard2.0\Fergun.Interactive.Local.dll because it was not found. Fergun.Interactive.Local C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets 4632

so I created a new library class project pointing to .net 6.0 and it gives me these errors in the InteractiveGuards
![image](https://github.com/d4n3436/Fergun.Interactive/assets/8949219/880cfca4-7fda-49f6-ae7d-b2ef20be6f9c)

![image](https://github.com/d4n3436/Fergun.Interactive/assets/8949219/784fa472-5f4e-4f09-92ba-a3639a50e3af)

**Comment by d4n3436** [comment]
The library can be built from source through Visual Studio with no problems. The library uses PolySharp to the use of C# 11 features on .NET Standard (like extended nameof scope). On .NET 6 you can use them by simply changing the language version to 11.

About your initial question, it's currently not possible to have multiple selections per message. It's someting I might fix at some point though.

**Comment by Jonasfxh** [comment]
The language version 11 was the first error I got when opening the project, I had to put a question mark in the language version.
![image](https://github.com/d4n3436/Fergun.Interactive/assets/8949219/0da15c20-2e63-4b97-b6d5-cc199ead5ce0)

**Comment by d4n3436** [comment]
You need the .NET 7 SDK to compile the project since it uses C# 11.

You can create a PR but it should not create breaking changes, or at least make them minimal.

**Comment by Jonasfxh** [comment]
Thank you! I changed to .net 7 and it's working fine.
