### ISSUE TITLE
Support for selection within paginator

### ISSUE THREAD

**Issue by SquirrelKiev** [d4n3436/Fergun.Interactive#30]
Not sure if this an option or not given the nature of supporting so many input methods but nevertheless, would it be possible to both have a paginator and a selection active on the same message? Would be useful for bots that allow searching an API.

![image](https://github.com/d4n3436/Fergun.Interactive/assets/41798511/4e6bb6a2-9ae4-40f9-89a2-37f8b503ff8e)

**Comment by SquirrelKiev** [comment]
(Just manually handling select menus for now.)

**Comment by d4n3436** [comment]
No, it's not really possible because they are incompatible. The supported solution is to add regular select menus with `PaginatorBuilder.AddSelectMenu()`.
