### ISSUE TITLE
Manually specified select menus do not appear on paginator if page length is same as max. 

### ISSUE THREAD

**Issue by SquirrelKiev** [d4n3436/Fergun.Interactive#31]
Title says it all. 

Image below should illustrate what I mean. I understand the buttons not showing as intended behaviour, however the select menu here were specified with the WithSelectMenus method, and should show whether buttons should be there or not afaik. 
![image](https://github.com/d4n3436/Fergun.Interactive/assets/41798511/816127b0-d80a-4ac6-9530-a00dd90a834a)

**Comment by SquirrelKiev** [comment]
This isn't an issue with ProcessSinglePagePaginators set to true in the config, of course.
![image](https://github.com/d4n3436/Fergun.Interactive/assets/41798511/b155abc5-159b-4c93-819c-ec44e5d44d4e)

**Comment by d4n3436** [comment]
It's intended behaviour as mentioned in the documentation of `ProcessSinglePagePaginators`:

> Gets or sets a value indicating if the SendPaginatorAsync() methods should completely process single-page paginators, that is, display their components, handle their inputs and wait for a result.

This applies to custom (detached) buttons and select menus too.
