### ISSUE TITLE
Create paginator with SelectMenu

### ISSUE THREAD

**Issue by BlyZeDev** [d4n3436/Fergun.Interactive#36]
I have a custom LazyPaginator and I want to add a SelectMenu choice to it.
Based on the choice the paginator should change and display something else.
I saw the `.AddSelectMenu()` but I don't get behind how to use it correctly.

My guess would be to create the Select Menu with an Id and do something when the component with this Id is used.
But I don't know how to access the paginator.

```cs
public sealed class ComponentModule : MyModuleBase
{
    public ComponentModule(InteractiveService interactive, IConfiguration config, ILogger logger)
        : base(interactive, config, logger) { }

    [ComponentInteraction(Constants.SelectMenuId, TreatAsRegex = false)]
    public async Task ExecuteSelectMenu()
    {
            //???
    }
```

**Comment by d4n3436** [comment]
You can get the paginator by casting the interaction into `SocketMessageComponent`, then using `interactive.TryGetPaginator()` and passing the message of the component interaction.

**Comment by BlyZeDev** [comment]
I'll try that, thank you :)

**Comment by BlyZeDev** [comment]
The ComponentInteraction doesn't even get fired for some reason

**Comment by BlyZeDev** [comment]
Fixed by adding the check for button component in `HandleInteractionAsync`
```cs
if (interaction is SocketMessageComponent component && component.Data.Type is ComponentType.Button)
{
    if (_interactive.IsManaged(interaction)) return;
}
```
